
package org.tdgames.agenda.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContactoService", targetNamespace = "http://service.agenda.tdgames.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContactoService {


    /**
     * 
     * @return
     *     returns java.util.List<org.tdgames.agenda.service.Contacto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerContactos", targetNamespace = "http://service.agenda.tdgames.org/", className = "org.tdgames.agenda.service.ObtenerContactos")
    @ResponseWrapper(localName = "obtenerContactosResponse", targetNamespace = "http://service.agenda.tdgames.org/", className = "org.tdgames.agenda.service.ObtenerContactosResponse")
    public List<Contacto> obtenerContactos();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.tdgames.agenda.service.Contacto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearContacto", targetNamespace = "http://service.agenda.tdgames.org/", className = "org.tdgames.agenda.service.CrearContacto")
    @ResponseWrapper(localName = "crearContactoResponse", targetNamespace = "http://service.agenda.tdgames.org/", className = "org.tdgames.agenda.service.CrearContactoResponse")
    public Contacto crearContacto(
        @WebParam(name = "arg0", targetNamespace = "")
        Contacto arg0);

}
